version: '3.3'

services:
  mongodb:
    image: mongo
    build: ./mongo
    restart: always
    env_file: dev.env
    container_name: mongodb
    restart: unless-stopped
    # command: mongod --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: surya
      MONGO_INITDB_ROOT_PASSWORD: mongodb123
      MONGO_INITDB_DATABASE: Audiobook
    volumes:
      - ./mongo/initdb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      # - mongodbdata:/data/db

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: dev.env
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./app/src/:/app/
    depends_on:
       - mongodb